# .github/workflows/build.yml
name: Build CFetch

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p CFetch-multiplatform/bin/${{ runner.os == 'macOS' && 'macos' || 'linux' }}
          if [ "${{ runner.os }}" == "macOS" ]; then
            clang cfetch.c -o CFetch-multiplatform/bin/macos/cfetch -D_OS_MACOS
          else
            gcc cfetch.c -o CFetch-multatform/bin/linux/cfetch -D_OS_LINUX
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: cfetch-binaries
          path: CFetch-multiplatform/bin/